version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
      - "8080:8080"
      - "27017:27017"

# docker-compose up --build
# docker-compose down -v
# tree -a -I ".git|team-photo|testimonial-pics"
